import type { Guide } from "./domain";

/** Illustrative editorial drafts only. Qualified review is required before publication or use. */
export const STARTER_GUIDES: Guide[] = [
  {
    slug: "squeaky-door-hinge",
    title: "A quieter door, one hinge at a time",
    summary: "Explore why an accessible interior door hinge might squeak, and what to check before considering routine care.",
    category: "Doors & windows",
    difficulty: "Easy",
    duration: "10–15 min",
    symptoms: ["Squeaking as an interior door moves", "Sound seems to come from a hinge"],
    tools: ["Soft cloth", "Manufacturer-approved hinge lubricant, if specified"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "An ordinary, undamaged interior door with all hinges within easy reach.", "Check the door and hinge manufacturer's care instructions first."],
    stopConditions: ["The door sags, binds, is heavy, or has loose or damaged fixings.", "The door is fire-rated, self-closing, glass, or part of an emergency exit.", "Access would require a ladder, hinge-pin removal, or supporting the door."],
    steps: [
      { title: "Locate the sound", description: "Draft review checkpoint: distinguish a hinge squeak from a door rubbing its frame. Keep fingers clear of moving gaps; do not loosen hinges.", partIds: ["hinge-frame", "hinge-door"], visual: {
        location: "Look along the edge where the door meets the frame. The two broad metal plates in this reference are the hinge leaves.",
        lookFor: "One leaf is attached to the stationary frame, the other to the moving door. A narrow vertical pivot joins them.",
        motion: "Observe only. The explode animation separates reference shapes; it is not a direction to move the real hinge.",
        force: "No force is required for visual identification. Do not pull the hinge pin or loosen supporting screws.",
        risk: "Loosening supporting hardware could let the door shift or fall. Fingers can be trapped in moving gaps.",
        check: "Can you distinguish the frame leaf from the door leaf without touching either? Pause if the arrangement differs.",
      } },
      { title: "Check the care guidance", description: "Confirm the hinge type and whether its manufacturer permits external lubrication. Sealed or specialist hinges may require different care.", partIds: ["hinge-pin"] },
      { title: "Plan a gentle clean", description: "A reviewer must confirm appropriate surface cleaning and any product application. This preview does not authorize removing pins or screws.", partIds: ["hinge-pin", "hinge-screws"] },
      { title: "Know when to stop", description: "If the source is uncertain, damage is visible, or the noise persists after approved care, ask a qualified repair professional to inspect it.", partIds: ["hinge-frame", "hinge-door"] },
    ],
    assemblyKind: "hinge",
    status: "draft",
    version: 1,
  },
  {
    slug: "loose-cabinet-knob",
    title: "Give a wobbly cabinet knob a little attention",
    summary: "Understand a simple knob's visible parts and identify when a loose fitting needs more than a routine adjustment.",
    category: "Furniture",
    difficulty: "Easy",
    duration: "5–10 min",
    symptoms: ["A cabinet knob turns or wobbles", "A small gap behind the knob"],
    tools: ["Correct-size hand screwdriver", "Soft cloth"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "A lightweight cabinet door at a comfortable working height.", "One visible, accessible fixing with no glass, electrical hardware, or specialist lock."],
    stopConditions: ["The wood is split, the screw spins freely, or the fixing is stripped.", "The panel is glass or the hardware includes a lock or electrical component.", "The door itself is loose or unstable."],
    steps: [
      { title: "Identify the fitting", description: "Compare the accessible knob with the manufacturer's instructions. The illustration shows a generic knob, washer, and screw—not your exact hardware.", partIds: ["knob-body", "knob-washer", "knob-screw"], visual: {
        location: "The round body is the cabinet knob held by hand. The illustrated screw and washer are behind it; do not dismantle your fitting to find them.",
        lookFor: "The washer is a flat ring; the screw is a narrow threaded fastener. A washing-machine control shaft is a different mechanism and is not represented here.",
        motion: "Identify shapes only. No pulling or turning direction is established by this example.",
        force: "Do not use pliers or apply force to an unidentified fitting. This visual checkpoint requires no adjustment.",
        risk: "Mistaking an appliance control shaft for a cabinet fixing could damage an internal mechanism. Appliance controls need exact-model guidance.",
        check: "Is this a simple cabinet fitting, rather than an appliance control? If uncertain, stop and request appropriate guidance.",
      } },
      { title: "Look for damage", description: "Check the visible panel and knob for cracking or distortion. A damaged panel needs assessment rather than a tighter fixing.", partIds: ["knob-body", "knob-washer"] },
      { title: "Confirm the permitted adjustment", description: "A reviewer must verify the right tool and any manufacturer-approved hand adjustment. Do not use a powered driver or force a resistant screw.", partIds: ["knob-screw", "knob-body"] },
      { title: "Check the outcome", description: "The fitting should be secure without crushing the panel. If wobble returns or the screw will not hold, stop and seek replacement-hardware advice.", partIds: ["knob-body"] },
    ],
    assemblyKind: "knob",
    status: "draft",
    version: 1,
  },
  {
    slug: "sticky-drawer",
    title: "Help a sticky drawer find its glide",
    summary: "Start with visible obstructions and drawer loading before assuming a runner needs repair.",
    category: "Furniture",
    difficulty: "Easy",
    duration: "10–15 min",
    symptoms: ["A lightweight drawer catches", "Uneven or scratchy movement"],
    tools: ["Soft brush", "Dry microfiber cloth"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "A stable, secured piece of furniture and a lightweight, reachable drawer.", "Manufacturer guidance permits cleaning the accessible track without drawer removal."],
    stopConditions: ["The furniture tips, shifts, or is not securely supported.", "A runner is bent, detached, or has loose sharp pieces.", "Access requires drawer removal, tools near a spring, or lifting a heavy load."],
    steps: [
      { title: "Check the surroundings", description: "Confirm the furniture is stable and the drawer is not overloaded. Never open several drawers together on an unstable unit.", partIds: [] },
      { title: "Look for an obstruction", description: "With fingers outside moving gaps, look for contents catching above or behind the drawer. Do not force it past resistance.", partIds: [] },
      { title: "Review accessible cleaning", description: "A reviewer must confirm the appropriate way to clear visible dust from this runner type. Do not assume oil or wax is suitable for every slide.", partIds: [] },
      { title: "Reassess the movement", description: "Continuing resistance, grinding, or an uneven drawer calls for hardware inspection rather than force or disassembly.", partIds: [] },
    ],
    status: "draft",
    version: 1,
  },
  {
    slug: "dirty-window-track",
    title: "A fresh start for a dusty window track",
    summary: "Recognize everyday track debris while keeping glass, drainage paths, and access safety in mind.",
    category: "Doors & windows",
    difficulty: "Easy",
    duration: "15–20 min",
    symptoms: ["Visible dust in a sliding window track", "A gritty feeling during normal operation"],
    tools: ["Soft brush", "Vacuum with brush attachment", "Microfiber cloth"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "An intact window safely accessible from inside at floor level.", "Manufacturer instructions allow cleaning without removing the sash or screen."],
    stopConditions: ["Glass is cracked, the sash is unstable, or the window will not stay safely positioned.", "You would need to lean outside, climb, or remove a sash.", "There is water ingress, rot, persistent mold, or a blocked drainage path you cannot identify."],
    steps: [
      { title: "Check safe access", description: "Identify a position that does not expose anyone to a fall or a closing sash. Keep children and pets away from open windows.", partIds: [] },
      { title: "Identify the track", description: "Distinguish loose surface debris from seals, drainage openings, and operating hardware. Do not scrape or cover unidentified openings.", partIds: [] },
      { title: "Review a gentle clean", description: "A reviewer must verify appropriate dry debris removal and any permitted damp cleaning. Avoid flooding the track or using abrasive products.", partIds: [] },
      { title: "Check for a different cause", description: "If normal movement is still difficult, stop. Misalignment, broken rollers, and glass problems are outside this draft's scope.", partIds: [] },
    ],
    status: "draft",
    version: 1,
  },
  {
    slug: "worn-weatherstrip",
    title: "Get to know the gap around your door",
    summary: "Learn what a worn surface seal looks like before choosing a compatible weatherstrip.",
    category: "Doors & windows",
    difficulty: "Easy",
    duration: "15–25 min",
    symptoms: ["A draft around an ordinary door", "A visibly worn or flattened surface seal"],
    tools: ["Tape measure", "Soft cloth", "Manufacturer-matched surface weatherstrip, if approved"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "An ordinary, non-fire-rated door that already opens and latches correctly.", "Only a manufacturer-approved, surface-applied draft seal is being considered."],
    stopConditions: ["The door is fire-rated, an emergency exit, or has a smoke-control seal.", "The gap relates to sagging, damaged framing, or water intrusion.", "A new strip could block ventilation, drainage, locking, or normal door closure."],
    steps: [
      { title: "Identify the existing seal", description: "Check the door documentation and visible seal type. A draft does not by itself establish that a weatherstrip is the right fix.", partIds: ["door-frame", "door-panel"], visual: {
        location: "Compare the stationary frame with the broad moving door panel. A surface seal may sit along their meeting edges, but the seal itself is not modeled.",
        lookFor: "The frame is the surrounding upright sides and top rail. The panel is the large wooden rectangle inside it.",
        motion: "Observe the visible edges only. On-screen separation is not an instruction to remove the door or seal.",
        force: "Apply no force for this checkpoint. Do not pry, pull, or scrape an unidentified strip.",
        risk: "A strip may serve smoke control, fire protection, ventilation, or drainage rather than ordinary draft sealing.",
        check: "Can you distinguish frame and panel, and confirm the door is not fire-rated? The reference cannot identify your actual seal.",
      } },
      { title: "Check the fit", description: "Record the visible gap and seal profile without altering the door. Do not cover intentional ventilation or drainage openings.", partIds: ["door-panel", "door-frame"] },
      { title: "Review compatibility", description: "A reviewer must confirm material compatibility, surface preparation, and manufacturer installation instructions before any replacement.", partIds: ["door-frame"] },
      { title: "Preserve normal operation", description: "Any approved replacement must leave the door able to open, latch, and lock normally. A binding door needs assessment, not extra closing force.", partIds: ["door-hinges", "door-handle"] },
    ],
    assemblyKind: "door",
    status: "draft",
    version: 1,
  },
  {
    slug: "slow-faucet-aerator",
    title: "Understand a faucet's little flow helper",
    summary: "Explore the screen at a faucet outlet and distinguish one-outlet flow issues from a wider plumbing problem.",
    category: "Plumbing",
    difficulty: "Easy",
    duration: "10–20 min",
    symptoms: ["Reduced flow at one faucet only", "An uneven stream at a visible aerator"],
    tools: ["Soft cloth", "Small parts tray", "Manufacturer-approved cleaning supplies"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "One cool, accessible outlet with an externally removable aerator confirmed by the manufacturer.", "No leaks, hot-water fault, contamination concern, or supply-wide pressure change."],
    stopConditions: ["Other outlets also have low flow, or there is an active leak.", "The outlet is hot, corroded, seized, hidden, or requires an unfamiliar special tool.", "The water has unexpected color or odor, or any fixture or supply pipe would need removal."],
    steps: [
      { title: "Compare the symptoms", description: "A reviewer should confirm that the issue is limited to one outlet. An aerator illustration cannot diagnose low supply pressure or water-quality problems.", partIds: ["aerator-housing"] },
      { title: "Identify the outlet parts", description: "Use the manufacturer's diagram to identify the housing, screen, and seal. Actual aerators may contain different or additional components.", partIds: ["aerator-housing", "aerator-screen", "aerator-gasket"] },
      { title: "Check permitted care", description: "A reviewer must validate whether user removal and cleaning are allowed, and the correct component order. Do not force fittings, use pliers, or remove the faucet.", partIds: ["aerator-screen", "aerator-gasket"] },
      { title: "Escalate if uncertain", description: "Persistent flow issues or any leak require qualified advice. Never infer hidden plumbing conditions from this generic model.", partIds: ["aerator-housing"] },
    ],
    assemblyKind: "aerator",
    status: "draft",
    version: 1,
  },
];
