import type { Guide } from "./domain";

export const GUIDE_PHOTOS: Partial<Record<string, { src: string; alt: string; caption: string; width: number; height: number }>> = {
  "washing-machine-control-knob": {
    src: "/examples/washing-machine-control-knob.png",
    alt: "Washing-machine timer dial with an exposed central shaft and a detached black control knob held below it.",
    caption: "Example photo: the knob is detached, while the dial and central shaft remain visible. The photo does not establish the failure, attachment type, dimensions, or exact washer model.",
    width: 1102,
    height: 1362,
  },
  "smart-thermostat-installation": {
    src: "/examples/smart-thermostat-installation.png",
    alt: "Round smart-thermostat base on a rectangular wall plate, with terminal blocks, loose colored wires, two mounting screws, and a drill nearby.",
    caption: "Supplied reference image: an exposed thermostat base with loose conductors. Do not copy the pictured tool use or wire arrangement. The photo does not establish power isolation, system voltage, wire functions, or compatibility.",
    width: 1130,
    height: 832,
  },
};

/** Illustrative editorial drafts only. Qualified review is required before publication or use. */
export const STARTER_GUIDES: Guide[] = [
  {
    slug: "squeaky-door-hinge",
    title: "A quieter door, one hinge at a time",
    summary: "Explore why an accessible interior door hinge might squeak, and what to check before considering routine care.",
    category: "Doors & windows",
    difficulty: "Easy",
    duration: "10–15 min",
    symptoms: ["Squeaking as an interior door moves", "Sound seems to come from a hinge"],
    tools: ["Soft cloth", "Manufacturer-approved hinge lubricant, if specified"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "An ordinary, undamaged interior door with all hinges within easy reach.", "Check the door and hinge manufacturer's care instructions first."],
    stopConditions: ["The door sags, binds, is heavy, or has loose or damaged fixings.", "The door is fire-rated, self-closing, glass, or part of an emergency exit.", "Access would require a ladder, hinge-pin removal, or supporting the door."],
    steps: [
      { title: "Locate the sound", description: "Draft review checkpoint: distinguish a hinge squeak from a door rubbing its frame. Keep fingers clear of moving gaps; do not loosen hinges.", partIds: ["hinge-frame", "hinge-door"], visual: {
        location: "Look along the edge where the door meets the frame. The two broad metal plates in this reference are the hinge leaves.",
        lookFor: "One leaf is attached to the stationary frame, the other to the moving door. A narrow vertical pivot joins them.",
        motion: "Observe only. The explode animation separates reference shapes; it is not a direction to move the real hinge.",
        force: "No force is required for visual identification. Do not pull the hinge pin or loosen supporting screws.",
        risk: "Loosening supporting hardware could let the door shift or fall. Fingers can be trapped in moving gaps.",
        check: "Can you distinguish the frame leaf from the door leaf without touching either? Pause if the arrangement differs.",
      } },
      { title: "Check the care guidance", description: "Confirm the hinge type and whether its manufacturer permits external lubrication. Sealed or specialist hinges may require different care.", partIds: ["hinge-pin"] },
      { title: "Plan a gentle clean", description: "A reviewer must confirm appropriate surface cleaning and any product application. This preview does not authorize removing pins or screws.", partIds: ["hinge-pin", "hinge-screws"] },
      { title: "Know when to stop", description: "If the source is uncertain, damage is visible, or the noise persists after approved care, ask a qualified repair professional to inspect it.", partIds: ["hinge-frame", "hinge-door"] },
    ],
    assemblyKind: "hinge",
    status: "draft",
    version: 1,
  },
  {
    slug: "loose-cabinet-knob",
    title: "Give a wobbly cabinet knob a little attention",
    summary: "Understand a simple knob's visible parts and identify when a loose fitting needs more than a routine adjustment.",
    category: "Furniture",
    difficulty: "Easy",
    duration: "5–10 min",
    symptoms: ["A cabinet knob turns or wobbles", "A small gap behind the knob"],
    tools: ["Correct-size hand screwdriver", "Soft cloth"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "A lightweight cabinet door at a comfortable working height.", "One visible, accessible fixing with no glass, electrical hardware, or specialist lock."],
    stopConditions: ["The wood is split, the screw spins freely, or the fixing is stripped.", "The panel is glass or the hardware includes a lock or electrical component.", "The door itself is loose or unstable."],
    steps: [
      { title: "Identify the fitting", description: "Compare the accessible knob with the manufacturer's instructions. The illustration shows a generic knob, washer, and screw—not your exact hardware.", partIds: ["knob-body", "knob-washer", "knob-screw"], visual: {
        location: "The round body is the cabinet knob held by hand. The illustrated screw and washer are behind it; do not dismantle your fitting to find them.",
        lookFor: "The washer is a flat ring; the screw is a narrow threaded fastener. A washing-machine control shaft is a different mechanism and is not represented here.",
        motion: "Identify shapes only. No pulling or turning direction is established by this example.",
        force: "Do not use pliers or apply force to an unidentified fitting. This visual checkpoint requires no adjustment.",
        risk: "Mistaking an appliance control shaft for a cabinet fixing could damage an internal mechanism. Appliance controls need exact-model guidance.",
        check: "Is this a simple cabinet fitting, rather than an appliance control? If uncertain, stop and request appropriate guidance.",
      } },
      { title: "Look for damage", description: "Check the visible panel and knob for cracking or distortion. A damaged panel needs assessment rather than a tighter fixing.", partIds: ["knob-body", "knob-washer"] },
      { title: "Confirm the permitted adjustment", description: "A reviewer must verify the right tool and any manufacturer-approved hand adjustment. Do not use a powered driver or force a resistant screw.", partIds: ["knob-screw", "knob-body"] },
      { title: "Check the outcome", description: "The fitting should be secure without crushing the panel. If wobble returns or the screw will not hold, stop and seek replacement-hardware advice.", partIds: ["knob-body"] },
    ],
    assemblyKind: "knob",
    status: "draft",
    version: 1,
  },
  {
    slug: "sticky-drawer",
    title: "Help a sticky drawer find its glide",
    summary: "Start with visible obstructions and drawer loading before assuming a runner needs repair.",
    category: "Furniture",
    difficulty: "Easy",
    duration: "10–15 min",
    symptoms: ["A lightweight drawer catches", "Uneven or scratchy movement"],
    tools: ["Soft brush", "Dry microfiber cloth"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "A stable, secured piece of furniture and a lightweight, reachable drawer.", "Manufacturer guidance permits cleaning the accessible track without drawer removal."],
    stopConditions: ["The furniture tips, shifts, or is not securely supported.", "A runner is bent, detached, or has loose sharp pieces.", "Access requires drawer removal, tools near a spring, or lifting a heavy load."],
    steps: [
      { title: "Check the surroundings", description: "Confirm the furniture is stable and the drawer is not overloaded. Never open several drawers together on an unstable unit.", partIds: [] },
      { title: "Look for an obstruction", description: "With fingers outside moving gaps, look for contents catching above or behind the drawer. Do not force it past resistance.", partIds: [] },
      { title: "Review accessible cleaning", description: "A reviewer must confirm the appropriate way to clear visible dust from this runner type. Do not assume oil or wax is suitable for every slide.", partIds: [] },
      { title: "Reassess the movement", description: "Continuing resistance, grinding, or an uneven drawer calls for hardware inspection rather than force or disassembly.", partIds: [] },
    ],
    status: "draft",
    version: 1,
  },
  {
    slug: "dirty-window-track",
    title: "A fresh start for a dusty window track",
    summary: "Recognize everyday track debris while keeping glass, drainage paths, and access safety in mind.",
    category: "Doors & windows",
    difficulty: "Easy",
    duration: "15–20 min",
    symptoms: ["Visible dust in a sliding window track", "A gritty feeling during normal operation"],
    tools: ["Soft brush", "Vacuum with brush attachment", "Microfiber cloth"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "An intact window safely accessible from inside at floor level.", "Manufacturer instructions allow cleaning without removing the sash or screen."],
    stopConditions: ["Glass is cracked, the sash is unstable, or the window will not stay safely positioned.", "You would need to lean outside, climb, or remove a sash.", "There is water ingress, rot, persistent mold, or a blocked drainage path you cannot identify."],
    steps: [
      { title: "Check safe access", description: "Identify a position that does not expose anyone to a fall or a closing sash. Keep children and pets away from open windows.", partIds: [] },
      { title: "Identify the track", description: "Distinguish loose surface debris from seals, drainage openings, and operating hardware. Do not scrape or cover unidentified openings.", partIds: [] },
      { title: "Review a gentle clean", description: "A reviewer must verify appropriate dry debris removal and any permitted damp cleaning. Avoid flooding the track or using abrasive products.", partIds: [] },
      { title: "Check for a different cause", description: "If normal movement is still difficult, stop. Misalignment, broken rollers, and glass problems are outside this draft's scope.", partIds: [] },
    ],
    status: "draft",
    version: 1,
  },
  {
    slug: "worn-weatherstrip",
    title: "Get to know the gap around your door",
    summary: "Learn what a worn surface seal looks like before choosing a compatible weatherstrip.",
    category: "Doors & windows",
    difficulty: "Easy",
    duration: "15–25 min",
    symptoms: ["A draft around an ordinary door", "A visibly worn or flattened surface seal"],
    tools: ["Tape measure", "Soft cloth", "Manufacturer-matched surface weatherstrip, if approved"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "An ordinary, non-fire-rated door that already opens and latches correctly.", "Only a manufacturer-approved, surface-applied draft seal is being considered."],
    stopConditions: ["The door is fire-rated, an emergency exit, or has a smoke-control seal.", "The gap relates to sagging, damaged framing, or water intrusion.", "A new strip could block ventilation, drainage, locking, or normal door closure."],
    steps: [
      { title: "Identify the existing seal", description: "Check the door documentation and visible seal type. A draft does not by itself establish that a weatherstrip is the right fix.", partIds: ["door-frame", "door-panel"], visual: {
        location: "Compare the stationary frame with the broad moving door panel. A surface seal may sit along their meeting edges, but the seal itself is not modeled.",
        lookFor: "The frame is the surrounding upright sides and top rail. The panel is the large wooden rectangle inside it.",
        motion: "Observe the visible edges only. On-screen separation is not an instruction to remove the door or seal.",
        force: "Apply no force for this checkpoint. Do not pry, pull, or scrape an unidentified strip.",
        risk: "A strip may serve smoke control, fire protection, ventilation, or drainage rather than ordinary draft sealing.",
        check: "Can you distinguish frame and panel, and confirm the door is not fire-rated? The reference cannot identify your actual seal.",
      } },
      { title: "Check the fit", description: "Record the visible gap and seal profile without altering the door. Do not cover intentional ventilation or drainage openings.", partIds: ["door-panel", "door-frame"] },
      { title: "Review compatibility", description: "A reviewer must confirm material compatibility, surface preparation, and manufacturer installation instructions before any replacement.", partIds: ["door-frame"] },
      { title: "Preserve normal operation", description: "Any approved replacement must leave the door able to open, latch, and lock normally. A binding door needs assessment, not extra closing force.", partIds: ["door-hinges", "door-handle"] },
    ],
    assemblyKind: "door",
    status: "draft",
    version: 1,
  },
  {
    slug: "slow-faucet-aerator",
    title: "Understand a faucet's little flow helper",
    summary: "Explore the screen at a faucet outlet and distinguish one-outlet flow issues from a wider plumbing problem.",
    category: "Plumbing",
    difficulty: "Easy",
    duration: "10–20 min",
    symptoms: ["Reduced flow at one faucet only", "An uneven stream at a visible aerator"],
    tools: ["Soft cloth", "Small parts tray", "Manufacturer-approved cleaning supplies"],
    prerequisites: ["Unreviewed draft: do not follow as approved repair instructions.", "One cool, accessible outlet with an externally removable aerator confirmed by the manufacturer.", "No leaks, hot-water fault, contamination concern, or supply-wide pressure change."],
    stopConditions: ["Other outlets also have low flow, or there is an active leak.", "The outlet is hot, corroded, seized, hidden, or requires an unfamiliar special tool.", "The water has unexpected color or odor, or any fixture or supply pipe would need removal."],
    steps: [
      { title: "Compare the symptoms", description: "A reviewer should confirm that the issue is limited to one outlet. An aerator illustration cannot diagnose low supply pressure or water-quality problems.", partIds: ["aerator-housing"] },
      { title: "Identify the outlet parts", description: "Use the manufacturer's diagram to identify the housing, screen, and seal. Actual aerators may contain different or additional components.", partIds: ["aerator-housing", "aerator-screen", "aerator-gasket"] },
      { title: "Check permitted care", description: "A reviewer must validate whether user removal and cleaning are allowed, and the correct component order. Do not force fittings, use pliers, or remove the faucet.", partIds: ["aerator-screen", "aerator-gasket"] },
      { title: "Escalate if uncertain", description: "Persistent flow issues or any leak require qualified advice. Never infer hidden plumbing conditions from this generic model.", partIds: ["aerator-housing"] },
    ],
    assemblyKind: "aerator",
    status: "draft",
    version: 1,
  },
  {
    slug: "washing-machine-control-knob",
    title: "A second chance for a washing-machine knob",
    summary: "Use a real detached washer button / timer-knob photo to explore the parts in 3D and plan a measured replacement, without guessing how it attaches.",
    category: "Appliances",
    difficulty: "Easy",
    duration: "20-30 min exploration",
    symptoms: ["A washing-machine control knob has come off", "An exposed shaft remains in the timer dial", "The detached knob may have a damaged hub or retainer"],
    tools: ["Exact-model manual and parts diagram", "Camera", "Calipers for a detached part only", "CAD software and 3D-printing service for a reviewed prototype"],
    prerequisites: [
      "Unreviewed draft: this is an educational 3D example, not approved installation guidance.",
      "Disconnect the washer from power before any physical inspection. If the plug is not safely accessible or the area is wet, stop and get qualified help.",
      "Identify the exact make, model, and replacement part number. The photo alone cannot establish compatibility.",
      "Scope is limited to the external, already-detached knob. Do not open the console, remove the dial, or disturb the timer mechanism.",
    ],
    stopConditions: [
      "The shaft is bent, loose, seized, or moves independently of the control mechanism.",
      "There are exposed wires, heat damage, moisture near electrics, or access requires opening the control panel.",
      "The attachment, damaged component, or manufacturer-approved installation method is uncertain.",
      "A proposed print replaces a metal retainer, spring, electrical part, or other load-bearing control component without qualified engineering approval.",
      "A replacement binds, slips, rubs the dial, or cannot preserve normal start/stop operation.",
    ],
    steps: [
      {
        title: "Compare the photo and the 3D parts",
        description: "The supplied photo shows a clear timer dial, an exposed central shaft, and a black knob held separately. Select each labeled part and use Explode view to understand their relationship. These are illustrative shapes, not a measured reconstruction.",
        partIds: ["washer-dial", "washer-shaft", "washer-knob"],
        visual: {
          location: "Find the circular dial in the middle of the control panel and the detached black knob below it.",
          lookFor: "The knob is separate from the dial. Metal features are visible, but their retention function and condition cannot be confirmed from this view.",
          motion: "Rotate or explode only the on-screen model. Separation on screen is not a removal or installation direction.",
          force: "No physical force is needed. Do not grip the exposed shaft with pliers.",
          risk: "Treating a timer shaft like a cabinet screw could damage the control or its start/stop function.",
          check: "Can you identify the dial, exposed shaft, and detached knob without assuming which part failed?",
        },
      },
      {
        title: "Identify the model and attachment",
        description: "Record the washer make/model from a safely accessible label and compare the exact parts diagram with the already-detached knob. Confirm whether the original part uses threads, a shaped socket, or a retainer. Do not assume a screw-on or push-fit connection from the photo.",
        partIds: ["washer-shaft", "washer-knob"],
        visual: {
          location: "Compare the back of the detached knob with the manufacturer's exploded parts diagram.",
          lookFor: "The original hub and any metal insert or retainer. The reference intentionally omits unverified internal attachment geometry.",
          motion: "The panel says turn right, pull to start, and push to stop; those are operating labels, not knob-removal instructions.",
          force: "Do not pull, twist, pry, or test the exposed shaft.",
          risk: "A wrong attachment can strip the shaft or leave the machine unable to stop normally.",
          check: "Record an exact part number and a documented attachment method before planning a replacement.",
        },
      },
      {
        title: "Measure before designing a replacement",
        description: "With power disconnected, measure only the already-detached knob: outside diameter, depth, hub dimensions, and any confirmed insert seat. Obtain mating-shaft specifications and required dial clearance from exact-model documentation or a qualified technician. Record all dimensions in millimeters; none can be recovered reliably from this single photo.",
        partIds: ["washer-knob", "washer-dial"],
        visual: {
          location: "Inspect the detached knob on a separate work surface, away from the appliance.",
          lookFor: "Cracks around the hub, missing pieces, and documented mating dimensions. Missing or broken surfaces are not reliable size references.",
          motion: "Use CAD to inspect a cross-section only after the attachment is documented.",
          force: "Do not use the exposed machine shaft as a sizing mandrel or force a test print onto it.",
          risk: "A visually similar socket may not transmit torque or axial push/pull loads correctly.",
          check: "A dimensioned sketch must include the confirmed interface, clearances, and retention method. Unknown measurements block fabrication.",
        },
      },
      {
        title: "Review the 3D-print concept",
        description: "Isolate the knob in the viewer to explore the outer grip. This model has no engineered socket, threads, or retainer and is not a printable replacement. For a real CAD design, a qualified reviewer must approve the measured interface, material, wall thickness, layer orientation, tolerances, and both turning and push/pull loads. Prefer the exact manufacturer replacement when those requirements are unknown.",
        partIds: ["washer-knob"],
        visual: {
          location: "Select Detached knob / replacement concept, then Isolate part to inspect the illustrative outer shape.",
          lookFor: "A broad hand grip and space for the documented hub. Hidden construction is deliberately not reconstructed.",
          motion: "On-screen rotation lets you view the concept from different angles; it does not establish a real fitting direction.",
          force: "No safe load rating or print settings have been established for this example.",
          risk: "A brittle or poorly fitting print can split, slip, or fail during a push-to-stop action. Do not substitute printed plastic for original metal retention hardware.",
          check: "Only a dimensioned, reviewed design can proceed to a non-operating fit sample and qualified assessment.",
        },
      },
      {
        title: "Confirm fit before returning to service",
        description: "A compatible replacement must be installed using the exact manufacturer's procedure with power disconnected. Have a qualified technician assess any unapproved printed part and verify secure retention, dial clearance, and full control travel. Do not power the washer to experiment with an uncertain repair; if compatibility or reliable stop operation cannot be established, use the correct original replacement.",
        partIds: ["washer-knob", "washer-shaft", "washer-dial"],
        visual: {
          location: "Compare the documented installed arrangement with the dial and external knob.",
          lookFor: "Correct alignment and clearance without rubbing, looseness, or a trapped dial.",
          motion: "Follow only the verified model-specific installation and commissioning procedure, not the explode animation.",
          force: "Never force a tight print, add glue to the shaft, or tighten an unidentified fitting.",
          risk: "A replacement that appears to fit may still fail to retain the knob or operate start/stop safely.",
          check: "Completing this walkthrough does not mean the washer is repaired. Keep it out of service until the replacement and normal control operation are verified.",
        },
      },
    ],
    assemblyKind: "washer-control",
    status: "draft",
    version: 1,
  },
  {
    slug: "smart-thermostat-installation",
    title: "Installing a Smart Thermostat? Here's What You Need to Know",
    summary: "Explore the visible thermostat parts in 3D, then review HVAC compatibility, power requirements, and the information a qualified installer needs before installation.",
    category: "Appliances",
    difficulty: "Easy",
    duration: "15-20 min planning",
    symptoms: ["Planning a smart thermostat upgrade", "Unsure about HVAC compatibility or a C-wire", "An exposed thermostat base with unidentified wires"],
    tools: ["Exact thermostat and HVAC model documentation", "Manufacturer compatibility checker", "Existing installation records or photos", "Qualified HVAC installer for electrical assessment"],
    prerequisites: [
      "Unreviewed draft: visual identification and pre-installation planning only. The Easy rating does not describe electrical installation.",
      "Do not touch the loose conductors shown. A qualified professional must identify and isolate all relevant power supplies and verify the safe state before any electrical work.",
      "Identify the exact thermostat, heating/cooling equipment, and control-system type from safely accessible documentation.",
      "Use the exact manufacturer's instructions and local requirements. The illustrative model is not a wiring diagram or a measured reconstruction.",
    ],
    stopConditions: [
      "Power isolation or system voltage is unknown; an off display does not prove that conductors are safe.",
      "Line-voltage controls, separate transformers, proprietary communication wiring, or an unsupported HVAC system are involved.",
      "Any wire function, terminal label, C-wire requirement, or manufacturer compatibility result is uncertain.",
      "Wiring is damaged, there are burn marks or moisture, or inspection requires opening equipment or disturbing conductors.",
      "Mounting would require drilling near unidentified wiring or pipes. Do not copy the drill placement in the photo.",
    ],
    steps: [
      {
        title: "Recognize the visible parts",
        description: "Compare the supplied photo with the rectangular trim plate, round mounting base, terminal blocks, loose conductors, and mounting screws in the model. The display is not shown. The neutral-colored model wires intentionally do not assign electrical functions.",
        partIds: ["thermostat-trim", "thermostat-base", "thermostat-terminals", "thermostat-wires", "thermostat-screws"],
        visual: {
          location: "Find the round base in the center of the rectangular wall plate. Conductors emerge through its center.",
          lookFor: "Two groups of terminal blocks sit beside the center opening, with mounting screws above and below.",
          motion: "Rotate, explode, or isolate the on-screen parts only. The animation does not show a real removal sequence.",
          force: "No physical contact or force is needed. Do not touch wires, operate the drill, or loosen screws.",
          risk: "The visible bare wire ends may be energized. The image cannot establish electrical safety.",
          check: "Can you name the visible components without inferring what any conductor controls?",
        },
      },
      {
        title: "Confirm system compatibility",
        description: "Use exact equipment documentation and the thermostat manufacturer's compatibility checker to establish whether the HVAC control system is supported. A similar-looking base does not prove compatibility. Refer line-voltage, proprietary, or unclear systems to a qualified installer.",
        partIds: ["thermostat-base", "thermostat-terminals"],
        visual: {
          location: "Treat the illustrated base as a shape reference; identify product and HVAC model numbers from documentation instead.",
          lookFor: "Documented control voltage, heating/cooling type, stages, and any manufacturer exclusions.",
          motion: "Do not remove equipment covers or move wires to collect missing information.",
          force: "No adjustment is permitted by this compatibility checkpoint.",
          risk: "Connecting a thermostat to an unsupported voltage or control system can damage equipment and create an electrical hazard.",
          check: "Is compatibility explicitly confirmed for both exact models? An unknown result means stop.",
        },
      },
      {
        title: "Record labels, not color guesses",
        description: "Have the installer review existing terminal records and the exact manufacturer's wiring diagram. Wire colors alone do not establish function, and the loose ends in this photo do not reveal their previous connections. This example deliberately provides no terminal-to-wire assignments.",
        partIds: ["thermostat-terminals", "thermostat-wires"],
        visual: {
          location: "The terminal blocks flank the central wiring opening. Their generic model shapes are not connection instructions.",
          lookFor: "Verified original terminal labels and documented conductor functions, not a guessed match based on insulation color.",
          motion: "Do not insert, disconnect, strip, bridge, or rearrange conductors using this reference.",
          force: "Do not push terminal tabs or pull wire ends.",
          risk: "A misplaced conductor or improvised jumper can short a transformer or cause unintended equipment operation.",
          check: "Does the installer have a verified connection record? Missing records cannot be reconstructed from this photo.",
        },
      },
      {
        title: "Review the C-wire and power requirements",
        description: "Confirm the exact thermostat's continuous-power requirements, including whether a common conductor or an approved manufacturer accessory is needed. A spare-looking wire, its color, or a visible C terminal does not prove a usable C-wire. Have a qualified installer assess both ends of the circuit.",
        partIds: ["thermostat-wires", "thermostat-terminals"],
        visual: {
          location: "Look at the conductors as a group; the model does not show the HVAC equipment end of the wiring.",
          lookFor: "An explicit power specification and a manufacturer-approved plan for this exact system.",
          motion: "No wiring change, live measurement, or adapter installation is demonstrated.",
          force: "Do not move a conductor to another terminal to experiment.",
          risk: "An unverified common connection or incompatible accessory can damage controls or lead to unreliable operation.",
          check: "Are the required power source and any approved accessory confirmed by the installer?",
        },
      },
      {
        title: "Plan mounting and professional commissioning",
        description: "Have the installer confirm a suitable wall location, secure mounting, hidden-service clearance, and the exact installation and commissioning procedure. Keep the system out of service if wiring or compatibility is uncertain. Completing this walkthrough does not establish that a thermostat is installed or safe to energize.",
        partIds: ["thermostat-trim", "thermostat-base", "thermostat-screws"],
        visual: {
          location: "The trim plate covers the wall surface; the round base and its fixings support the thermostat assembly.",
          lookFor: "A documented mounting plan and manufacturer commissioning checks for the actual HVAC equipment.",
          motion: "The exploded screws show component relationships only, not a drilling or fastening procedure.",
          force: "No drilling or tightening force is specified. Do not copy the powered tool shown near exposed wires.",
          risk: "Drilling can strike hidden services; incorrect setup can command heating or cooling unexpectedly.",
          check: "A qualified installer must verify secure installation, electrical safety, and normal operation before handover.",
        },
      },
    ],
    assemblyKind: "thermostat",
    status: "draft",
    version: 1,
  },
];
