import Link from "next/link";
import { ArrowRight, ArrowUpRight, Camera, Mic, MessageSquareText, ShieldCheck, Check, Search, Wrench, Sparkles } from "lucide-react";
import HomeIllustration from "@/components/home-illustration";
import GuideCard from "@/components/guide-card";
import { STARTER_GUIDES } from "@/lib/catalog";
import { hasConvex } from "@/lib/config";

export default function HomePage() {
  return <>
    <section className="hero container"><div className="hero-copy"><div className="eyebrow hero-eyebrow"><span/>HOME REPAIRS, MADE SIMPLE</div><h1>A little help.<br/><span>A better home.</span></h1><p className="hero-description">That drip, squeak, or wobble? Let&apos;s figure it out.<br className="desktop-break"/> Get clear guidance for the small fixes that make<br className="desktop-break"/> a big difference.</p><Link href="/problems/new" className="button hero-button">Let&apos;s fix something <ArrowUpRight size={19}/></Link><div className="input-methods"><Link href="/problems/new?input=text"><MessageSquareText size={16}/>Describe it</Link><Link href="/problems/new?input=photo"><Camera size={16}/>Snap a photo</Link><Link href="/problems/new?input=audio"><Mic size={16}/>Talk it through</Link></div><div className="hero-reassurance"><ShieldCheck size={16}/>A little know-how. No guesswork.</div></div><HomeIllustration/></section>
    <div className="benefit-strip"><div className="container benefits"><span><Check size={17}/>Simple, step-by-step guidance</span><span><Check size={17}/>See how the parts fit together</span><span><Check size={17}/>Know when to call a pro</span></div></div>
    <section className="section container"><div className="section-heading"><div><span className="eyebrow">SMALL FIXES, BIG SATISFACTION</span><h2>A good place to start.</h2><p>Everyday home hiccups. A little less mystery.</p></div><Link className="text-link" href="/catalog">Explore all fixes <ArrowRight size={18}/></Link></div>{!hasConvex && <p className="preview-note"><Sparkles size={15}/>Preview — draft content. Explore the experience; guides need review before use.</p>}<div className="guide-grid home-guides">{STARTER_GUIDES.slice(0, 3).map(guide => <GuideCard key={guide.slug} guide={guide}/>)}</div>{hasConvex && <p className="small muted">Illustrative starting points. Find reviewed, available guidance in <Link href="/catalog">the published catalog</Link>.</p>}</section>
    <section className="how-section" id="how-it-works"><div className="container"><div className="center-heading"><span className="eyebrow">YOU&apos;VE GOT THIS. WE&apos;VE GOT YOU.</span><h2>From “what&apos;s that?” to “got it.”</h2><p>A simpler way to understand what your home needs.</p></div><div className="steps-grid">{[{icon:MessageSquareText, title:"Tell us what’s going on",text:"Type a few words, share a photo, or record a voice note. Start with what you know."},{icon:Search,title:"Make sense of the problem",text:"Get a cautious suggestion, helpful follow-up questions, and a clear next step."},{icon:Wrench,title:"Take it one small step at a time",text:"Explore the parts and follow reviewed guidance. If it’s not a DIY job, we’ll say so."}].map((step,i) => <div className="how-step" key={step.title}><div className="step-icon"><step.icon size={28}/><span>0{i+1}</span></div><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></div></section>
    <section className="container section safety-section"><div className="safety-icon"><ShieldCheck size={37}/></div><div><span className="eyebrow">CONFIDENCE, NOT OVERCONFIDENCE</span><h2>Sometimes the best fix is a professional.</h2><p>We stick to small, low-risk repairs. Electrical, gas, structural issues, or major leaks? Stop and get qualified help. Your safety always comes first.</p></div><Link href="/privacy#safety" className="text-link">Our safety approach <ArrowRight size={18}/></Link></section>
    <section className="container bottom-cta"><div><span className="eyebrow">HOME FEELS BETTER WHEN THINGS WORK.</span><h2>What can we help you fix?</h2><p>You don&apos;t need to know the name of the part. Just start here.</p></div><Link href="/problems/new" className="button">Describe a problem <ArrowUpRight size={19}/></Link></section>
  </>;
}
